### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by jounathaen** [ncm2/ncm2-syntax#3]
I'm new to ncm2 and I have no Idea, for which kind of syntax this plugin is written. A tiny bit more information in the README might help ;-)

**Comment by jsfaint** [comment]
This plugin is a source for ncm2 based on neco-syntax.

You can refer the doc of neco-syntax https://github.com/Shougo/neco-syntax/blob/master/doc/necosyntax.txt

neco-syntax gathers syntax data from vim syntax file.
This plugin will use these data for completion.

**Comment by jsfaint** [comment]
And one more thing this plugin is out-of-box after installation

**Comment by jounathaen** [comment]
Thanks for the information. This would already be an improvement of the README. (Even though I have to admit, that after reading the necosyntax.txt I still don't know what the benefits are. But this might be a problem of neco-syntax).
Sorry to bother here, but the ncm2 wiki points to this repository without any further explanation what this is.

**Comment by jsfaint** [comment]
Yeah, you're right.
I'll add more information and screencast when I get some spare time.

neco-syntax supports differents filetypes except vimscript, because it is covered by neco-vim
neco-syntax provides source for language keywords for completion
like: `if`, `while`, `for`, `switch`, `case` and etc in C. which is defined in `syntax/c.vim`

**Comment by jsfaint** [comment]
I added description and demonstration  in readme

**Comment by jounathaen** [comment]
Great! Thanks for your Work!
